---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  become: true

- name: Add Python Repository
  ansible.builtin.apt_repository:
    repo: ppa:deadsnakes/ppa
    state: present
  become: true

- name: Install Python
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop:
    - "python{{ pyhton_install_version }}"
    - "python{{ pyhton_install_version }}-venv"
    - "python{{ pyhton_install_version }}-dev"
    - "python{{ pyhton_install_version }}-distutils"
  become: true

- name: Set Python Version
  ansible.builtin.command: "update-alternatives --install /usr/bin/python3 python3 /usr/bin/python{{ pyhton_install_version }} 1"
  changed_when: false
  when: pyhton_install_set_version
  become: true

- name: Switch Python Version
  ansible.builtin.command: "update-alternatives --set python3 /usr/bin/python{{ pyhton_install_version }}"
  changed_when: false
  when: pyhton_install_set_version
  become: true
