---
- name: Check if Python Version Installed
  ansible.builtin.command: python{{ pyhton_install_version }} --version
  register: python_version_installed
  changed_when: false
  failed_when: false
  ignore_errors: true

- name: Run OS specific tasks
  ansible.builtin.include_tasks: "{{ ansible_os_family }}.yml"
  when: python_version_installed != pyhton_install_version

- name: Check if Pip Installed
  ansible.builtin.command: pip{{ pyhton_install_version }} --version
  register: pip_version_installed
  changed_when: false
  failed_when: false
  ignore_errors: true

- name: Pip Install
  ansible.builtin.include_tasks: install-pip.yml
  when: pip_version_installed.rc != 0

- name: Upgrade Pip
  ansible.builtin.pip:
    name: pip
    state: latest
