---
- name: Run OS specific tasks
  include_tasks: "{{ ansible_os_family }}.yml"

- name: Get Pip Installer
  ansible.builtin.get_url:
    url: https://bootstrap.pypa.io/get-pip.py
    dest: /tmp/get-pip.py
    mode: '0755'

- name: Install Pip
  ansible.builtin.command: python{{ version }} /tmp/get-pip.py

- name: Remove Pip Installer
  ansible.builtin.file:
    path: /tmp/get-pip.py
    state: absent
